import './globals.css'
import Nav from "./components/navbar/Nav"
import { Inter as FontSans } from "next/font/google"
import ClientOnly from './components/ClientOnly';
import ToasterProvider from './providers/ToasterProvider';
import LoginModal from '@/app/components/modals/LoginModal';
import RegisterModal from '@/app/components/modals/RegisterModal';
import { ThemeProvider } from './providers/ThemeProvider';
import getCurrentUser from './actions/getCurrentUser';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const font = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
})
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  console.log(currentUser)
  return (
    <html lang="en">
      <body className={`min-h-screen bg-white font-sans text-slate-900 antialiased dark:bg-slate-900 dark:text-slate-50 ${font.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ClientOnly>
            <ToasterProvider />
            <LoginModal />
            <RegisterModal />
            <Nav currentUser={currentUser} />
          </ClientOnly>
          <div className="pb-20 pt-28">
            {children}
          </div>
        </ThemeProvider>
      </body>
      
    </html>
  )
}
